/*
 * This file is generated by jOOQ.
 */
package com.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserMaster implements Serializable {

    private static final long serialVersionUID = 702460125;

    private Integer userId;
    private String  name;

    public UserMaster() {}

    public UserMaster(UserMaster value) {
        this.userId = value.userId;
        this.name = value.name;
    }

    public UserMaster(
        Integer userId,
        String  name
    ) {
        this.userId = userId;
        this.name = name;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserMaster other = (UserMaster) obj;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserMaster (");

        sb.append(userId);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
